### PR TITLE
Cross compile scalafix input and output with 2.11, 2.12 and 2.13

### PR DESCRIPTION
**Pull request by MasseGuillaume**
With this PR I make sure the CrossCompat rules does compile in 2.11, 2.12 and 2.13. This is a bit envolve since we need to have a static sbt build (we cannot set the scalaVersion with crossScalaVersion). Another difficulty is to make sure all the test are discovered with scalafix-testkit. Finally, we need to update the ci to match the new static build.

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
@julienrf good to go. This should unblock me for SortedMap.unsorted.

File: project/Version.scala [hunk 1]
```diff
@@ -0,0 +1,18 @@
+case class Version(major: Int, minor: Int, patch: Int) {
```
Comment (MasseGuillaume) [inline project/Version.scala]: @julienrf alternatively, we could use scalacenter/versions if you merge https://github.com/scalacenter/versions/pull/3 and push a tag.

File: scalafix/input/src/main/scala/fix/BreakoutSrc.scala [hunk 2]
```diff
@@ -58,7 +58,7 @@ class BreakoutSrc(ts: Traversable[Int], vec: Vector[Int], list: List[Int], seq:
   (ts ++ ts )(breakOut): Set[Int]
 
   // `TraversableLike ++:`
-  (ts ++: ts)(breakOut): Set[Int]
+  // (ts ++: ts)(breakOut): Set[Int]
```
Comment (MasseGuillaume) [inline scalafix/input/src/main/scala/fix/BreakoutSrc.scala]: I have to figure out this one, the rewritten output does not cross-compile.

File: scalafix/input/src/main/scala/fix/BreakoutSrc.scala [hunk 3]
```diff
@@ -97,10 +97,8 @@ class BreakoutSrc(ts: Traversable[Int], vec: Vector[Int], list: List[Int], seq:
   List(1 -> "1").map(x => x)(breakOut): immutable.HashMap[Int, String]
   List(1 -> "1").map(x => x)(breakOut): immutable.ListMap[Int, String]
   List(1 -> "1").map(x => x)(breakOut): immutable.TreeMap[Int, String]
-  List(1 -> "1").map(x => x)(breakOut): mutable.SortedMap[Int, String]
```
Comment (MasseGuillaume) [inline scalafix/input/src/main/scala/fix/BreakoutSrc.scala]: mutable.SortedMap is only available in 2.12+

File: scalafix/output/src/main/scala/fix/BreakoutSrc.scala [hunk 4]
```diff
@@ -58,7 +58,7 @@ class BreakoutSrc(ts: Iterable[Int], vec: Vector[Int], list: List[Int], seq: Seq
   (ts.iterator ++ ts ).to(scala.collection.immutable.Set): Set[Int]
 
   // `TraversableLike ++:`
-  (ts ++: ts.view).to(scala.collection.immutable.Set): Set[Int]
+  // (ts ++: ts)(breakOut): Set[Int]
```
Comment (MasseGuillaume) [inline scalafix/output/src/main/scala/fix/BreakoutSrc.scala]: This does not compile in 2.13.0-M4.

```scala
value ++: is not a member of scala.collection.View[Int]
```
I think it will be solved via this PR: https://github.com/scala/scala/pull/6674

Comment (julienrf) [reply scalafix/output/src/main/scala/fix/BreakoutSrc.scala]: I see, that’s because we don’t have `++:` on `Iterable`.

**Comment by MasseGuillaume** [comment]
@julienrf can you merge this PR? Thanks.
